//
// $Id$

package com.threerings.gwt.ui;

import com.google.gwt.user.client.ui.Label;

import com.threerings.gwt.util.Value;

/**
 * Displays a dynamically changing value. Automatically handles regenerating its contents when the
 * value changes and registers and clears its listenership when it is added to and removed from the
 * DOM.
 */
public class ValueLabel<T> extends Label
    implements Value.Listener<T>
{
    /**
     * Creates a value label with the supplied value. When this label is added to the DOM, its text
     * will be generated by a call to {@link #getText} with the value's current value. It will also
     * add itself as a listener at that point and update its text whenever the value changes.
     */
    public ValueLabel (Value<T> value)
    {
        _value = value;
    }

    /**
     * Creates a value label with the supplied value and CSS style.
     */
    public ValueLabel (String styleName, Value<T> value)
    {
        this(value);
        setStyleName(styleName);
    }

    // from Value.Listener<T>
    public void valueChanged (T value)
    {
        setText(getText(value));
    }

    @Override // from Widget
    public void onLoad ()
    {
        super.onLoad();
        _value.addListener(this);
        valueChanged(_value.get());
    }

    @Override // from Widget
    public void onUnload ()
    {
        super.onLoad();
        _value.removeListener(this);
    }

    /**
     * Called to generate our text when the value changes. The default implementation simply
     * converts the value to a string via {@link String#valueOf}.
     */
    protected String getText (T value)
    {
        return String.valueOf(value);
    }

    /** The value we're displaying. */
    protected Value<T> _value;
}
